services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: paymentlab
      POSTGRES_USER: paymentlab
      POSTGRES_PASSWORD: paymentlab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "random_page_cost=1.1"

  issuer:
    build:
      context: .
      dockerfile: Dockerfile.issuer
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgres://paymentlab:paymentlab@postgres:5432/paymentlab?sslmode=disable
      ISSUER_LISTEN: 0.0.0.0:5001
    depends_on:
      - postgres

  acquirer:
    build:
      context: .
      dockerfile: Dockerfile.acquirer
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://paymentlab:paymentlab@postgres:5432/paymentlab?sslmode=disable
      ISSUER_ADDR: issuer:5001
      ACQUIRER_PORT: 8081
      MAX_CONCURRENT: 500
      MAX_QUEUE: 100000
      QUEUE_TIMEOUT_SEC: 60
    depends_on:
      - postgres
      - issuer

volumes:
  pgdata:
